spring:
  application:
    name=SpringSecurityTest
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123456
    url: jdbc:postgresql://localhost:5432/Test
    username: postgres
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          hbm2ddl:
            auto: update
          show_sql: true
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type: TRACE
